namespace Panlingo.LanguageIdentification.Lingua
{
    /// <summary>
    /// Language supported by Lingua
    /// </summary>
    public enum LinguaLanguage : byte
    {
        Afrikaans = 0,
        Albanian = 1,
        Arabic = 2,
        Armenian = 3,
        Azerbaijani = 4,
        Basque = 5,
        Belarusian = 6,
        Bengali = 7,
        Bokmal = 8,
        Bosnian = 9,
        Bulgarian = 10,
        Catalan = 11,
        Chinese = 12,
        Croatian = 13,
        Czech = 14,
        Danish = 15,
        Dutch = 16,
        English = 17,
        Esperanto = 18,
        Estonian = 19,
        Finnish = 20,
        French = 21,
        Ganda = 22,
        Georgian = 23,
        German = 24,
        Greek = 25,
        Gujarati = 26,
        Hebrew = 27,
        Hindi = 28,
        Hungarian = 29,
        Icelandic = 30,
        Indonesian = 31,
        Irish = 32,
        Italian = 33,
        Japanese = 34,
        Kazakh = 35,
        Korean = 36,
        Latin = 37,
        Latvian = 38,
        Lithuanian = 39,
        Macedonian = 40,
        Malay = 41,
        Maori = 42,
        Marathi = 43,
        Mongolian = 44,
        Nynorsk = 45,
        Persian = 46,
        Polish = 47,
        Portuguese = 48,
        Punjabi = 49,
        Romanian = 50,
        Russian = 51,
        Serbian = 52,
        Shona = 53,
        Slovak = 54,
        Slovene = 55,
        Somali = 56,
        Sotho = 57,
        Spanish = 58,
        Swahili = 59,
        Swedish = 60,
        Tagalog = 61,
        Tamil = 62,
        Telugu = 63,
        Thai = 64,
        Tsonga = 65,
        Tswana = 66,
        Turkish = 67,
        Ukrainian = 68,
        Urdu = 69,
        Vietnamese = 70,
        Welsh = 71,
        Xhosa = 72,
        Yoruba = 73,
        Zulu = 74,
    }
}
