using System;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Panlingo.LanguageIdentification.MediaPipe.SourceGenerator
{
    [Generator]
    public class MediaPipeGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var modelDataProvider = context.AnalyzerConfigOptionsProvider
                .Select((options, cancellationToken) => FetchModelDataAsync().Result);

            context.RegisterSourceOutput(modelDataProvider, (sourceProductionContext, modelDataString) =>
            {
                if (!string.IsNullOrEmpty(modelDataString))
                {
                    var className = $"{nameof(MediaPipe)}ResourceProvider";
                    var sourceBuilder = new StringBuilder();

                    sourceBuilder.AppendLine($@"
                    byte[] bytes = Base64Decode(""{modelDataString}"");
                    DefaultModel = bytes;
                    ");

                    var code = $@"
    // <auto-generated/>
    using System;
    using System.Collections.Generic;

    namespace {nameof(Panlingo)}.{nameof(LanguageIdentification)}.{nameof(MediaPipe)}
    {{
        public static class {className}
        {{
            public static readonly byte[] DefaultModel;

            static {className}()
            {{
                {sourceBuilder}
            }}

            static byte[] Base64Decode(string base64EncodedData) 
            {{
                var result = System.Convert.FromBase64String(base64EncodedData);
                return result;
            }}
        }}
    }}
                    ";

                    sourceProductionContext.AddSource($"{className}.g.cs", SourceText.From(code, Encoding.UTF8));
                }
            });
        }

        private static async Task<string> FetchModelDataAsync()
        {
            var modelUrl = "https://storage.googleapis.com/mediapipe-models/language_detector/language_detector/float32/1/language_detector.tflite";
            using (var httpClient = new HttpClient())
            {
                var modelData = await httpClient.GetByteArrayAsync(modelUrl);
                return Base64Encode(modelData);
            }
        }

        public static string Base64Encode(byte[] bytes)
        {
            return Convert.ToBase64String(bytes);
        }
    }
}
